spring.application.name=foodiesapi

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/foodies}

# Local file uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Security
logging.level.org.springframework.security=INFO
jwt.secret.key=${JWT_SECRET_KEY}

# Razorpay
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}
